### ISSUE TITLE
Extension errors in console if git repository is local only

### ISSUE THREAD

**Issue by ecool** [swdotcom/swdc-vscode#265]
**Describe the bug**
Extension prints an error whenever the current directory is a local git repo (no remote).
Problem code seems to be here:
https://github.com/swdotcom/swdc-vscode/blob/210282392d40df47d147a72b76f285d915f7b426/src/repo/KpmRepoManager.ts#L115
I am not sure if this is causing further issues with the extension or if it only prints an error.
```paste below
command error:  Error: Command failed: git config --get remote.origin.url
    at checkExecSyncError (child_process.js:639:11)
    at execSync (child_process.js:675:15)
    at electron/js2c/asar_bundle.js:5:12113
    at Object.t.execCmd (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:85721)
    at Object.<anonymous> (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:123622)
    at Generator.next (<anonymous>:null:null)
    at c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:123201
    at new Promise (<anonymous>:null:null)
    at n (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:122946)
    at Object.A [as getResourceInfo] (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:123412)
    at c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:86964
    at Generator.next (<anonymous>:null:null)
    at c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:86328
    at new Promise (<anonymous>:null:null)
    at n (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:86073)
    at p (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:86817)
    at Object.<anonymous> (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:88508)
    at Generator.next (<anonymous>:null:null)
    at c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:86328
    at new Promise (<anonymous>:null:null)
    at n (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:86073)
    at Object.t.incrementEditorSeconds (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:88408)
    at A.<anonymous> (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:401:93246)
    at Generator.next (<anonymous>:null:null)
    at c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:401:92630
    at new Promise (<anonymous>:null:null)
    at n (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:401:92375)
    at Timeout._onTimeout (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:401:93025)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
 (at Object.t.execCmd (c:\Users\ecool\.vscode-insiders\extensions\softwaredotcom.swdc-vscode-2.5.10\dist\extension.js:5:85914))
```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

1. Create new directory
2. Initialize a git repo (git init) in the directory
3. Open VSCode and open the developer tools and switch to the console tab
4. Wait for everything to initialize and the error will show up

**Expected behavior**
The extension should fail silently without displaying an error.

**ACTUAL RESULTS**

The error described above is displayed in the console.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Plugin version: 2.5.10

**Additional context**
- VSCode
- VSCode Insiders

**Comment by xavluiz** [comment]
Hi, and thank you for the issue report. We'll look at this right away. The details were very helpful.
Regards.

**Comment by xavluiz** [comment]
Hi @ecool. Yes, its a caught error and not causing issues with the code time logic. We have a PR that will prevent the git commands from executing if its not a git directory and its not yet part of a remote repo. We'll get this released sometime today or early tomorrow after testing. Thanks again for bringing this up.
Regards.

**Comment by ecool** [comment]
Awesome, @xavluiz. Thanks for looking into it and glad that it wasn't causing issues with the tracking.

**Comment by xavluiz** [comment]
No problem. We've release 2.5.11 with the fix mentioned above. Let us know if there's anything else and thank you again for your help identifying the issue.

**Comment by ecool** [comment]
Alright, seeing as the error no longer shows up. I'll be closing the issue.
