### ISSUE TITLE
Stack bug

### ISSUE THREAD

**Issue by syzgod** [swdotcom/swdc-vscode#422]
VS Code Version: 1.72.2
OS Version: Ubuntu 22.04.1 LTS
Plugin version: 2.6.33

Hello everyone!

I'm getting this error on Code Time after everything is loaded in VScode:

**Activating extension 'softwaredotcom.swdc-vscode' failed: Maximum call stack size exceeded.
$onExtensionActivationError @ mainThreadExtensionService.ts:111**

Any idea why?

**Comment by flerpo** [comment]
Yeah, me to. Worked last week 

[2022-10-26 20:19:14.648] [exthost] [error] Activating extension softwaredotcom.swdc-vscode failed due to an error:
[2022-10-26 20:19:14.648] [exthost] [error] RangeError: Maximum call stack size exceeded
	at splitPath (node:electron/js2c/asar_bundle:5:747)
	at e.existsSync (node:electron/js2c/asar_bundle:5:6372)
	at P (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:922135)
	at k (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:921822)
	at F (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:921965)
	at _ (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:921265)
	at H (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:922529)
	at U (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:922274)
	at o (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:946264)
	at t.getJsonItem (c:\Users\*\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.33\dist\extension.js:2:946567)

**Comment by syzgod** [comment]
> Thank you for the information. We'll look into this right away.

Thank you. Anyway, everything is fine in Windows 11 but even after reinstalling the extension in VScode it is still now working in Ubuntu sadly.

**Comment by daZepelin** [comment]
I am having the same issue for like half a year now and simply can't use the extenstion since.
Output in the `Extenstion Host` is similar:
```
2023-01-26 09:31:51.274 [info] ExtensionService#_doActivateExtension softwaredotcom.swdc-vscode, startup: false, activationEvent: 'onStartupFinished'
2023-01-26 09:31:54.241 [error] Activating extension softwaredotcom.swdc-vscode failed due to an error:
2023-01-26 09:31:54.241 [error] RangeError: Maximum call stack size exceeded
    at splitPath (node:electron/js2c/asar_bundle:5:747)
    at Object.e.existsSync (node:electron/js2c/asar_bundle:5:6372)
    at P (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:967976)
    at D (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:967663)
    at F (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:967806)
    at C (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:967106)
    at U (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:968246)
    at t.logIt (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:970476)
    at a (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:988599)
    at t.getJsonItem (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:988902)
    at C (c:\Users\vytut\.vscode\extensions\softwaredotcom.swdc-vscode-2.6.42\dist\extension.js:2:967105)
 ```
And the extenstion Tab only comes up with: `An error occurred while loading view: codetime.webView`

Tried reinstalling the extenstion multiple times, even reinstalled VSC at some point. Seems to work on my another Windows server machine now as well as Windows 11 one, but on my Windows 10 still can't get it to work.
