### ISSUE TITLE
Code Time not working

### ISSUE THREAD

**Issue by harisdev-netizen** [swdotcom/swdc-vscode#515]
**Describe the bug**
```CODE TIME NOT LOADING

```
**ISSUE TYPE**
- Bug Report

**Steps to reproduce**

**Expected behavior**
```paste below

```

**ACTUAL RESULTS**

```The Code Time VS Code extension is not working since last two or maybe three days.

```

**Screenshots**
![image](https://github.com/user-attachments/assets/88d744aa-0431-4de9-866d-9325d346387d)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Plugin version [e.g. Code Time v1.2.1]

**Additional context**
```paste below

```

**Comment by daika7ana** [comment]
Can confirm.
Version 2.8.2 is broken. Downgrading to 2.8.1 fixes it, and that version works.
Something broke in between those 2 versions.

**Comment by bjacobson26** [comment]
Hi @harisdev-netizen and @daika7ana,

We're having trouble reproducing the problem on v2.8.2. Are you still experiencing it?

Some suggestions:
1. quit VSCode and reopen it. 
2. Log out of CodeTime and log back in. You can logout by using the command palette:
<img width="626" alt="image" src="https://github.com/user-attachments/assets/f0e39e23-b3d8-4a7f-80d7-3328a5198f3e">

Thank you.

**Comment by daika7ana** [comment]
I am running the following VSCode under Windows 11 24H2:
```
Version: 1.95.1 (system setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.26100
```

After updating to Code Time v2.8.2 Extension host produces the following error:
```
2024-11-05 23:30:10.132 [error] Activating extension softwaredotcom.swdc-vscode failed due to an error:
2024-11-05 23:30:10.132 [error] TypeError: File URL path must be absolute
	at getPathFromURLWin32 (node:internal/url:1459:11)
	at fileURLToPath (node:internal/url:1492:35)
	at 49553 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1121517)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1273824)
	at 23086 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:810185)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1273824)
	at 27690 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:825426)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1273824)
	at 42702 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:807361)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1273824)
	at c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1274433
	at c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1276751
	at Object.<anonymous> (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.2\dist\extension.js:2:1276772)
	at Module._compile (node:internal/modules/cjs/loader:1484:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
	at Module.load (node:internal/modules/cjs/loader:1295:32)
	at Module._load (node:internal/modules/cjs/loader:1111:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:174:10879)
	at t._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:22433)
	at i._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:158:4651)
	at Module.require (node:internal/modules/cjs/loader:1318:19)
	at require (node:internal/modules/helpers:179:18)
	at z_.xb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:166:23753)
	at async Promise.all (index 0)
```

Code Time from the sidebar is stuck in a loading loop as the screenshot posted above by the issue starter. 
Running any Code Time command from the Command Palette gives the following error:
![image](https://github.com/user-attachments/assets/91950e68-493c-444b-976b-3fcd6b6e364e)

**Comment by bjacobson26** [comment]
Thanks for the detailed error report. we'll look into it asap and get back to you.

**Comment by harisdev-netizen** [comment]
> Hi @harisdev-netizen and @daika7ana,
> 
> We're having trouble reproducing the problem on v2.8.2. Are you still experiencing it?
> 
> Some suggestions:
> 
> 1. quit VSCode and reopen it.
> 2. Log out of CodeTime and log back in. You can logout by using the command palette:
> 
> <img alt="image" width="626" src="https://private-user-images.githubusercontent.com/9271952/383322196-f0e39e23-b3d8-4a7f-80d7-3328a5198f3e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4OTkzNTYsIm5iZiI6MTczMDg5OTA1NiwicGF0aCI6Ii85MjcxOTUyLzM4MzMyMjE5Ni1mMGUzOWUyMy1iM2Q4LTRhN2YtODBkNy0zMzI4YTUxOThmM2UucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDZUMTMxNzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE5MjhjNDMxZjhlM2EwOGQwNGU5ZmVlMDQ2MzM3ZGYzYTM0MzUyMTk0ODU5OGZiZDQzNGM0NzVlMDI2N2YzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Brdq5sPFgx-f9yN3VgBdnN8lIWFv7_wW7NdFQk2NKrQ">
> Thank you.

Tried quitting VS Code and then Re-Opening it many times but still the issue remains.

**Comment by daika7ana** [comment]
> This PR should resolve the issue: #517
> 
> we'll get it merged and deploy a release as soon as possible.

Much appreciated. 
I was also suspecting the `open` npm library to be the culprit. 
However I did try compiling with both 9.1.0 and 10.1.0, and both worked while building locally.

Nevertheless, updated to v2.8.3 and it's working.

**Comment by harisdev-netizen** [comment]
> This PR should resolve the issue: #517
> 
> we'll get it merged and deploy a release as soon as possible.

Much appreciated

**Comment by daika7ana** [comment]
@bjacobson26 @xavluiz 

Apologies for tagging you both. Since the last release, the open JS library was updated, which has caused this regression. We're seeing the same error as before, caused by the same culprit.


Currently running VSCode ver:
```
Version: 1.100.2 (system setup)
Commit: 848b80aeb52026648a8ff9f7c45a9b0a80641e2e
Date: 2025-05-14T21:47:40.416Z
Electron: 34.5.1
ElectronBuildId: 11369351
Chromium: 132.0.6834.210
Node.js: 20.19.0
V8: 13.2.152.41-electron.0
OS: Windows_NT x64 10.0.26100
```

Extension host error:
```
2025-05-27 12:15:08.433 [error] Activating extension softwaredotcom.swdc-vscode failed due to an error:
2025-05-27 12:15:08.433 [error] TypeError: File URL path must be absolute
	at getPathFromURLWin32 (node:internal/url:1459:11)
	at fileURLToPath (node:internal/url:1492:35)
	at 49553 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1175396)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1328221)
	at 23086 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:810184)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1328221)
	at 27690 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:825415)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1328221)
	at 42702 (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:807361)
	at n (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1328221)
	at c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1328830
	at c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1331148
	at Object.<anonymous> (c:\Users\USERNAME\.vscode\extensions\softwaredotcom.swdc-vscode-2.8.4\dist\extension.js:2:1331169)
	at Module._compile (node:internal/modules/cjs/loader:1544:14)
	at Module._extensions..js (node:internal/modules/cjs/loader:1629:10)
	at Module.load (node:internal/modules/cjs/loader:1282:32)
	at Module._load (node:internal/modules/cjs/loader:1103:12)
	at c._load (node:electron/js2c/node_init:2:16955)
	at e._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:225:1509)
	at t._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:180:22628)
	at r._load (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:172:22062)
	at Module.require (node:internal/modules/cjs/loader:1305:19)
	at require (node:internal/modules/helpers:182:18)
	at PJ.Cb (file:///c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:211:1253)
```

**Comment by xavluiz** [comment]
Hi @daika7ana, thank you. We're looking into this now and will provide an update soon. Thank you for the stack trace.
Regards.
